### PR TITLE
docs: add information on running Flux interactively on CORAL

### PR DESCRIPTION
**Pull request by wihobbs**
Now that we have the LSF URI resolver, we should add some documentation so users can take advantage of its utility.

We should probably wait until we release & tag flux-core@0.42.0 and get that built on BlueOS to merge this.

### CODE REVIEW

**Comment by wihobbs** [comment]
Updating commit message -- just looked through our issues and I believe this will close #70.

**Comment by garlick** [comment]
Nicely done!  And thanks for finding that issue.

**Review by garlick — APPROVED** [review]
Oops this should have been merged a while back!

**Comment by wihobbs** [comment]
The `make-check` issue should be fixed but the `make-linkcheck` is failing because LC confluence is behind an auth wall.

**Comment by grondo** [comment]
Thanks @wihobbs! sphinx has a [`linkcheck_ignore`](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=linkcheck#confval-linkcheck_ignore) setting we can use to ignore all links in LC confluence if you want to try that?

**Comment by wihobbs** [comment]
Hi @grondo! Will do.

**Comment by wihobbs** [comment]
I put some more time into this and I couldn't seem to get `linkcheck_ignore` to work; however, I found that the direct jump to "RZAnsel users should verify SSH keys" (after the hashtag in the link) was causing the problem, so I just removed that. If a user is able to navigate to the quickstart guide, they should be able to find this pretty easily anyway. Fixed and pushed.

Someone should probably click the link and make sure it still works just as a sanity check (I don't have access to LC confluence anymore...)

**Comment by grondo** [comment]
Thanks I approved the workflow to run and looks like it succeeded! :+1:

**Comment by wihobbs** [comment]
Thanks @grondo! and tysm @jameshcorbett for the fix-up :)

**Pull request merged**
