### PR TITLE
adminguide: use single TOML files for examples

### PR DESCRIPTION
**Pull request by garlick**
This PR switches the admin config file examples over to using one big example file (for each of the three config spaces) rather than a lot of little files that might be annoying to sys admins.

The examples are not all-inclusive.  accounting, prolog/epilog, and validator configs are still presented in separate "add on" sections.  I did do some re-titling of sections and tweaked the header level in some cases.

Maybe give the rendered version a read and see if it's any better?   I'm not hard over on this change, but I do think it might be a little better than before.

### CODE REVIEW

**Comment by garlick** [comment]
I just realized this includes the proposed change in #137 to remove the note about `flux ion-R`.  I can fix that if needed.

**Review by grondo — APPROVED** [review]
Wow, this reads _much_ better in my opinion! I also think admins will appreciate seeing a large chunk of configuration all in one place, rather than piecemeal in the document. 

This was a large amount of work, thanks!

**Comment by grondo** [comment]
>  I just realized this includes the proposed change in #137 to remove the note about flux ion-R. I can fix that if needed.

Hm, seems like we could just merge as is and drop the other PR if that's more efficient (it is just documentation anyway)

**Comment by garlick** [comment]
Thanks!   I just fixed a typo and re-pushed.  Well based on that glowing review, maybe I'll just set MWP then :smile:

**Pull request merged**
