### PR TITLE
Remove hyphen in "sub-instance"

### PR DESCRIPTION
**Pull request by chu11**
"sub-instance" should not be hyphenated.

### CODE REVIEW

**Review by vsoch — APPROVED** [review]
I don't have a strong opinion about the hyphen or not, but I'm OK to remove it if others agree it's better.

**Comment by chu11** [comment]
why is mergify not doing its thing ... lets try and kick it

**Comment by chu11** [comment]
@Mergifyio rebase

**Comment by chu11** [comment]
https://github.com/Mergifyio rebase

**Pull request merged**
