### PR TITLE
Integrating RFC as a subproject

### PR DESCRIPTION
**Pull request by gonsie**

### CODE REVIEW

**Comment by gonsie** [comment]
Hot dog! Check out the docs now! https://flux-framework--38.org.readthedocs.build/en/38/

**Comment by garlick** [comment]
Eureka! This even looks fabulous on my phone!

Jim

**Comment by garlick** [comment]
One nit - links from the rfc index don't seem to be resolving for me.

**Comment by gonsie** [comment]
The RFC index not resolving is a separate issue (see flux-framework/rfc#242). I’ll work on resolving that separately. This PR just gets the pages from the flux-docs repo to correctly link to the pages from the rfc repo.

I’ll remove the wip label and fix my commits, then it’ll be ready when everyone else is happy.

**Pull request merged**
