### PR TITLE
rabbit: add docs on rabbit_datamovements

### PR DESCRIPTION
**Pull request by jameshcorbett**
Problem: there is no documentation for the rabbit_datamovements KVS entry.

Add docs.

### CODE REVIEW

**Review by wihobbs — APPROVED** [review]

**Comment by jameshcorbett** [comment]
@wihobbs not sure what happened to mergify can you merge this for me?

**Comment by wihobbs** [comment]
@mergifyio refresh

**Comment by wihobbs** [comment]
Hmm. Ok sure

**Comment by wihobbs** [comment]
It must've gotten confused with the add/remove but I'm surprised refresh didn't fix that. Oh well

**Pull request merged**
