### PR TITLE
adminguide: update for release 0.21.0

### PR DESCRIPTION
**Pull request by garlick**
Update all notes/warnings that refer to the specific version.

Shorten a couple of section names to make them more general and
clear.

Fix whitespace.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM, thanks! Do we need to add anything about resource configuration via "R"? That could always come in a follow-on PR if necessary.

**Comment by garlick** [comment]
Oh good idea - probably a new section.  Perhaps we could come up with a `flux R` command line to generate fluke's config?  Want to propose that in another PR?

I was also thinking maybe I should sync the config examples that happen to use fluke with the actual fluke config (assuming hostlist change is merged in 0.21).  I'll do that and tack on a commit to this PR shortly.

**Comment by grondo** [comment]
> Perhaps we could come up with a flux R command line to generate fluke's config? Want to propose that in another PR?

Yeah, another PR sounds good.

**Comment by garlick** [comment]
OK to set MWP?

**Comment by grondo** [comment]
Yes!

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
