### PR TITLE
coral: how to run with specific resource set and affinity

### PR DESCRIPTION
**Pull request by dongahn**
Fix Issue #48 per @rcarson3's request.

### CODE REVIEW

**Comment by dongahn** [comment]
@rcarson3: could you give a quick look at this and let me know if this is sufficient? 

manpage of `flux-mini` is [here](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-mini.html).

**Comment by rcarson3** [comment]
@dongahn it looks fine to me. If the `flux-mini` points to the most up to date version that might also be nice to include in there as well just to make it easier for users to find.

**Comment by dongahn** [comment]
@grondo or @garlick: per @rcarson3's feedback, do you know how to create a link from `flux-mini` to its manage rendered in our readthedoc?

**Comment by dongahn** [comment]
Thanks @rcarson3 for the quick review as well.

**Comment by garlick** [comment]
You mean replace the mention of `flux-mini(1)` in the coral doc with a link?  I believe it's something like this (and don't forget the trailing `_`):
```
`flux-mini(1) <https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-mini.html>`_
```

**Comment by dongahn** [comment]
> don't forget the trailing _)

:-) Yap devil' in the details. Thanks.

**Comment by dongahn** [comment]
@garlick: just forced a push with the manpage link. Could you an explicit approval so that we can MWP?

**Review by garlick — APPROVED** [review]
LGTM!

**Comment by dongahn** [comment]
Thanks @garlick !

**Pull request merged**
