### PR TITLE
comics: add why is flux?

### PR DESCRIPTION
**Pull request by garlick**
Problem: some people only read comic books.  How are they going to learn about the world of supercomputing?

Start a comic series.

Scribbled on a Remarkable tablet and uploaded.

### CODE REVIEW

**Comment by vsoch** [comment]
OMG! AMAZING!! :raised_hands: I love comics!!

**Comment by vsoch** [comment]
:laughing: 
image

**Comment by vsoch** [comment]
"Do some science or something!" :laughing: 
image
SHEESH

**Comment by vsoch** [comment]
"Yes it is astonishing!"

image

okay we've reached laughing tears... I think I'm almost done reading...

**Comment by vsoch** [comment]
It's the Fluxiverse!! 
image

**Review by vsoch — APPROVED** [review]
This is the most creative, hilarious, and majestic piece of documentation art I have ever seen! On the level of Julia Evans but for our very own Flux!! @garlick I am :raised_hands: and I absolutely love this and approve!!

OK with you if I share in our Twitter spaces / Mattermost / yell about the new pages from the mountaintops? I used to draw bad comics in another life (usually just 1-3 frames) so maybe I could contribute a one-off one too :)

**Comment by garlick** [comment]
Thank you  for saying nice things :smiley: 

I wasn't sure if it was OK to slot this silliness into the main index?

Also, I'm happy to edit based on comments.  This is kind of a sloppy, tossed-off mess.

So maybe let's go slow?

**Comment by vsoch** [comment]
> So maybe let's go slow?

I'm happy to do what the group wants - I think it's fabulous and I'd be OK with imperfections and just merge, but if others are more strict, we can keep working on it. The only other place I thought it might go well is as a "Comics" section under Guide (that's where I first went looking for it and then saw it in the main index).

**Comment by vsoch** [comment]
And @garlick here is my tiny collection of comics! https://vsoch.github.io/2023/cartoons/ The best two are "Cookie Vulnerability" and "Compiling" and I had to stop because my Windows machine (with Photoshop) crashed. It was a great way to take little funny jokes from chat / just in my head and put them down. I would totally love to pick this up again, even if I'm kind of terrible at it, and I think this idea of making comics for documentation is so spot on - entertaining and (can be) informative too! 

We just started a converged computing guide - currently just text in a document - but I could see using this strategy to explain some of the concepts in a fun way!

**Comment by grondo** [comment]
[Pokey the Penguin](https://www.yellow5.com/pokey/archive/) level brilliance!

**Comment by garlick** [comment]
> https://vsoch.github.io/2023/cartoons/ 

@vsoch - wow I'm impressed!  I especially liked the ear one :-)

**Comment by vsoch** [comment]
>  @vsoch - wow I'm impressed! I especially liked the ear one :-)

It's funny because it's the unspoken truth :laughing:

**Comment by garlick** [comment]
> The only other place I thought it might go well is as a "Comics" section under Guide (that's where I first went looking for it and then saw it in the main index).

I think of the guide section as containing some fairly in-depth docs since that's where the admin guide is and we've put a fair amount of work into that and keep it updated.

**Comment by chu11** [comment]
awesome!  I love it.  Only one minor comment, comic is a tad lab centric, mentioning director's office and hotline. Could slightly tweak to be more generic?  Maybe hotline isn't a huge deal.  Perhaps of directors office, ask "sure, how much money you got?"

**Comment by cmoussa1** [comment]
Nice work!! Once this lands, this would be awesome to promote on our twitter account!!

**Comment by garlick** [comment]
The "good enough for twitter" bar is pretty low so OK :-)

I'll make @chu11's suggested changes.  I wish there were a more discrete way to link this to the top page.  Anybody have any ideas on that one?  What about a "don't click here" link at the very bottom?

**Comment by chu11** [comment]
oh yeah i didn't mention last night

image

I'm seeing a couple extra box lines ... is this just me?

**Comment by garlick** [comment]
Eh part of the template I used on the Remarkable.  Not sure if I can get rid of it.  I'll try.

**Comment by garlick** [comment]
Lab specificity removed,  storyboard template replaced wtih hand drawn frames, and index link moved to after "glossary".

**Comment by chu11** [comment]
with this I think we declare flamingo our mascot.  Do we need a name?

**Comment by vsoch** [comment]
> with this I think we declare flamingo our mascot. Do we need a name?

Fernando, Frank, Francisco, Finn, Frederick, Fred, Felipe... should start with an "F" right?

**Comment by chu11** [comment]
lol, "Fortran the Flamingo" ... although Fortran might be trademarked

**Comment by garlick** [comment]
Any objections if I set MWP?

**Comment by chu11** [comment]
DO IT!

**Comment by vsoch** [comment]
Wooo!! Can I share widely?

**Comment by vsoch** [comment]
@cmoussa1 do you want to tweet on the main Flux twitter first and I'll retweet?

**Comment by garlick** [comment]
It's a free country!  I'll go hide.

**Comment by vsoch** [comment]
@garlick I have a tablet thing that I unearthed, and I ordered a new battery for the stylus - I'm going to give a shot at venturing back into comics drawing land when it arrives in the mind! I think I'm going to start with maybe some single panels with the penguin, and moving forward when I have bad mental imagery / jokes instead of just laughing to myself I'll write it down!

**Pull request merged**
