### PR TITLE
Add manager comparison table

### PR DESCRIPTION
**Pull request by vsoch**
This is a WIP! I have a css/javascript bug somewhere that the last few rows are missing colors, but wanted to share the WIP for quick feedback, etc.

image

Unless I embedded some html table library to customize this, I couldn't find a way for the simple list-table in rst to support having full width rows every once in a while, so I opted for three separate tables (and I think it looks OK?)  I'm also planning on adding some text that guides the reader to the right places if they want to suggest a feature to add, or point out we are wrong about something.

Finally, note that the same code renders on its own page (above) and the FAQ (below)

image

Here is the original png for comparison.

image

I'm going for my run because it's been a day, but I'll be back and hopefully have more patience for JavaScript after that. :laughing:  Back in a bit!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
okay fixed the bugs, this is ready for review! This is maybe the one thing I didn't epically fail on today. :sob: :laughing: 

image
image

**Comment by vsoch** [comment]
Preview! https://flux-framework--190.org.readthedocs.build/en/190/tables/comparison-table.html and the table is also in the FAQ. I think questions for discussion are:

- where on the site we should put the table vs link it (e.g., I'm not sure it belongs fully in the FAQ but the link makes sense
- should it also be part of the portal (or another FAQ that links to it from there?)

**Comment by cmoussa1** [comment]
Wow this looks really awesome! Great work on this so far @vsoch. 👍

> where on the site we should put the table vs link it (e.g., I'm not sure it belongs fully in the FAQ but the link makes sense

IMHO, something substantial like this probably warrants its own page on the site instead of just a FAQ entry. However, I definitely think it's worth mentioning a table like this on the FAQ page and providing a link to it. So, under the question "How does Flux compare to other resource managers?" an answer could say something like:

"Flux has similarities to many other resource managers, but we do a variety of things quite differently. Check out this comparison table **here** (insert hyperlink) for a detailed list!"

Or maybe something along those lines. I've never been a strong writer 😅 lol

> should it also be part of the portal (or another FAQ that links to it from there?)

Just my thoughts, but keeping a table like this in just one spot makes the most sense to me. Especially if we want to add/edit rows or columns in the future. We could always link to it throughout the portal wherever we feel appropriate.

**Comment by vsoch** [comment]
> IMHO, something substantial like this probably warrants its own page on the site instead of just a FAQ entry. 

Yep - it has it's own page! I will update the table on the FAQ page to just be the link, and update with the text you provided.

Changes coming soon!

**Comment by vsoch** [comment]
Done!

**Comment by vsoch** [comment]
I'm so excited to merge! I can't wait to share with everyone. I spent like half a day on this table, specifically figuring out how to make it, lol.

_insert Jurassic Park reference... she's learning!!_

**Comment by garlick** [comment]
That really did turn out nice!  Thanks @vsoch !

**Comment by grondo** [comment]
One quick question about the content. The table row labeled `Bulk job submission` states "Uniform jobs only" for Slurm, but though I could be confused about what is meant by bulk job submission in this context, Slurm does have [Job Arrays](https://slurm.schedmd.com/job_array.html), which seem to be a non-uniform bulk submission feature.

Not sure if that warrants a change in that row for Slurm since I'm not sure of the intent there, but thought I'd point it out since the table should at least appear fair...

**Comment by garlick** [comment]
The job array description says
> All jobs must have the same initial options (e.g. size, time limit, etc.), however it is possible to change some of these options after the job has begun execution using the scontrol command specifying the JobID of the array or individual ArrayJobID.

So I can see where the authors might think the statement is fair.  (I'm not knowledgeable about this feature of slurm so I guess I'm not adding much here)

**Comment by chu11** [comment]
dumb nuance question, if there is only one language binding (Moab's "some (C)"), shouldn't the column just say "no"?  Perhaps my interpretation of "binding" is different than others.  But the way I think of it, there's the "base" language and bindings against that language.  So if only the base language is supported, there are no bindings?

**Comment by vsoch** [comment]
I think for this PR it should be scoped to adding the current (published?) table, and any changes that are wanted should be followed up separately.

**Comment by garlick** [comment]
Agreed.  Feel free to set the merge when passing tag for mergify since @cmoussa1 already approved.

**Comment by vsoch** [comment]
Can I merge it then? :D

**Comment by vsoch** [comment]
oh it already happened, yay!!!

**Comment by garlick** [comment]
Mergify does that for you and rebases on current master if needed.

**Pull request merged**
