### PR TITLE
faqs: add how to input unicode U+0192

### PR DESCRIPTION
**Pull request by garlick**
Problem: people want to know how to type a fancy f.

Add some instructions.

Feel free to push additional info here (anybody program a ƒ key macro?)

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
important info to know!

**Comment by garlick** [comment]
Just pushed instructions for Konsole configuration as noted in flux-framework/flux-core#4540

**Review by chu11 — APPROVED** [review]
still LGTM

**Comment by garlick** [comment]
Well what the heck, MWP then!

**Pull request merged**
