### PR TITLE
docs: add a flux-accounting section

### PR DESCRIPTION
**Pull request by cmoussa1**
#### Background

As the flux-accounting project continues to mature and become more of a part of system-instance Flux, it would be nice to have more documentation about the specifics of flux-accounting, such as database administration, job usage and fair-share information, the multi-factor priority plugin, and more. It might also be nice if this documentation was easy to locate alongside the other Flux components.

---

This is a small [WIP] PR that adds a separate page in flux-docs that adds more details about the flux-accounting sub-project. For the purposes of keeping this PR somewhat simple (and hopefully easy to review!), I've only added one sub-section: a sub-section that outlines basic database administration and a glossary. 

I've written this guide with the intended audience of an administrator (someone who is going to be using flux-accounting), but if perhaps a change of direction would be better, let me know. :-)

I am very much open to any and all feedback on how to make this documentation more clear. For example, if specific database administration examples would help (e.g showing how to use the `add-*` or `edit-*` commands, I would be more than happy to add those.

In the near future, I plan on submitting subsequent PR's that add sections to this page on some of the other major components of flux-accounting, which may include:

- job usage and fairshare documentation
  - examples of how usage is calculated
- multi-factor priority plugin
  - what factors are used, how they affect job priority calculation
  - accounting limits (`max_active_jobs`, `max_running_jobs`)

### CODE REVIEW

**Comment by garlick** [comment]
This is excellent!  I had two quick thoughts:
- consider adding a glossary for terms like "bank" and "association"
- should we consider moving the accounting section in the flux admin guide to here and leaving a reference there?

**Comment by cmoussa1** [comment]
> consider adding a glossary for terms like "bank" and "association"

Yes, I like this suggestion, thank you! I've already added a *glossary* for _association_, but it would definitely be worth adding a definition for a bank too (along with all the other accounting-specific terms once they are added to this document). I'll add a _bank_ definition before I mark this as ready for review.

> should we consider moving the accounting section in the flux admin guide to here and leaving a reference there?

I like this suggestion too - I wonder, though, if it might be worth leaving the basic installation/configuration instructions for flux-accounting in the flux admin guide, and moving any nitty gritty details (like database administration, for example) to this document. :-) Just my opinion though. Does that make sense and would be okay with you?

**Comment by garlick** [comment]
Oh duh!  In my quick skim I must have registered your glossary subliminally and then it became my idea!  Wow.  Brain not working right.

Sure, I'm ok with leaving the admin guide stuff where it is.   The two guides can be complementary.

**Comment by cmoussa1** [comment]
Lol, no problem! Glad we are on the same page! I've just pushed an additional definition of a _bank_, and I'll go ahead and mark this as ready for some review whenever convenient. Thanks for your review and suggestions so far.

**Review by garlick — APPROVED** [review]
Great start!  LGTM!

**Comment by cmoussa1** [comment]
Thanks @garlick! Setting MWP

**Pull request merged**
