### PR TITLE
[WIP] accounting guide: insert a dummy change

### PR DESCRIPTION
**Pull request by cmoussa1**
#### Problem

We're trying to figure out why the auto examples generation is acting up with a simple name change in one of the `.rst` files.

---

This PR makes a dummy change to one of the guides to see if the auto examples generation still fails. This PR should not be merged, but just to see if the auto examples generation in GitHub actions still fails.

### CODE REVIEW

**Comment by cmoussa1** [comment]
@wihobbs looks like this PR failed too with the same error message:

```
😢️ Auto examples were not updated! Different size of index.rst:
  1497 vs. 1557
```

Perhaps we need to open an issue on this? I wonder if something is acting up with GitHub actions? 🤷

**Comment by grondo** [comment]
@vsoch, any ideas?

**Comment by wihobbs** [comment]
I think this would be fixed with a rebase since I pushed changes to address it in #272. In any case, @cmoussa1 want to close?

**Comment by cmoussa1** [comment]
OK, I'll close here. Thanks

**Pull request closed without merging**
