### PR TITLE
Use preferred capitalization of "Slurm"

### PR DESCRIPTION
**Pull request by wickberg**
https://slurm.schedmd.com/faq.html#acronym

### CODE REVIEW

**Comment by vsoch** [comment]
Thanks @wickberg - your changes look good! It looks like readthedocs is expecting a different format (a specific field os) for the readthedocs.yaml. I'll debug this and see if I can get it fixed up and then we can rebase here.

**Comment by vsoch** [comment]
hey @wickberg ! If you could please rebase the fix for readthedocs was just merged. Thanks!

**Comment by wickberg** [comment]
Should be rebased, but it looks like a maintainer needs to poke things to get the final check to run?

**Comment by vsoch** [comment]
@wickberg I am a maintainer and I have been approving the checks for you.

**Review by vsoch — APPROVED** [review]

**Pull request merged**
