### PR TITLE
fluxion: drop use of flux-ion-R to augment the system R

### PR DESCRIPTION
**Pull request by dongahn**
Problem: flux-ion-R augments the R encoded by flux-R for our fluxion
scheduler. However, the full R with the scheduling key (with which we
have a system resource graph) is difficult to manage and debug at the
system-instance level. To fix this problem, we just added rv1exec reader
support directly into the fluxion scheduler (flux-sched PR #9210)
and we now need our documentation update accordingly.

Remove the prose on flux-ion-R from the admin guide section.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
Thanks, @dongahn! Should we wait to merge this until latest Fluxion is tagged and released?

**Comment by dongahn** [comment]
>Thanks, @dongahn! Should we wait to merge this until latest Fluxion is tagged and released?

Yes, if that has been our practice, we should wait until the next version is tagged/released.

**Comment by garlick** [comment]
#139 was just merged and it was convenient to just include this change there, so I'll go ahead and close this one.  Thanks!

**Comment by dongahn** [comment]
Thanks!

**Pull request closed without merging**
