### PR TITLE
admin guide: add how to generate R for fluxion

### PR DESCRIPTION
**Pull request by dongahn**
This PR adds a simple instruction into the admin guide section on how to generate R for the Fluxion scheduler.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM, might want to add an explanatory comment about why `flux ion-R` is required for Fluxion (appends information to _R_ required for graph-based scheduling or somesuch), but the current text is straight and to the point if you'd rather not elaborate.

**Comment by dongahn** [comment]
Good point. I will add a sentence or two to explain it.

**Comment by dongahn** [comment]
@grondo: I added those changes and squashed them.

**Review by grondo — APPROVED** [review]
Yeah, looks good @dongahn!

**Review by SteVwonder — APPROVED** [review]
LGTM too!

**Pull request merged**
