### PR TITLE
comics: tell the story of Fluxbird's demise

### PR DESCRIPTION
**Pull request by garlick**
Problem: fans of Fluxonomicon are expecting Chapter 2.

Kill off the main character.

@vsoch I really didn't want to see your radish creation fall off the slack history!  Hope you don't mind.

### CODE REVIEW

**Comment by chu11** [comment]
Isn't there an old saying, like no comic character ever truly dies?  We can multiverse him back to life later :-)

**Comment by chu11** [comment]
Or systemd allows fluxbird to continue running?

**Comment by garlick** [comment]
Right, we'll just restart him from an earlier checkpoint.

**Comment by vsoch** [comment]
Oh that’s hilarious! 😂 

You can’t count on me for much, but you can count on me to eat main characters when they turn into vegetables.

**Review by chu11 — APPROVED** [review]

**Pull request merged**
